name: Lobby
author: Yassino
version: 1.0
main: de.teamholy.lobby.Lobby

depend: [CloudNet-Bridge ,HolographicDisplays, bukkit-core]
softdepend: [CloudNet-Bridge, HolographicDisplays, bukkit-core]

commands:
  test1:
  spawn: